# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff-check
        entry: poetry run ruff check --fix --force-exclude
        language: python
        types_or: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format --force-exclude
        language: python
        types_or: [python]
        args: []
        require_serial: true
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: python
        types_or: [python]
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: node
        entry: npx eslint
        args: [--fix]
        types_or: [ts]
        additional_dependencies:
          - eslint-plugin-prettier
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: node
        entry: npx prettier
        args: [--write]
        types_or: [ts]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: tsconfig.json
      - id: check-added-large-files
